import Foundation

// Only the four native media actions generated by supported Siri Remote buttons.
// No keyboard text or mouse events enter this policy.
enum AppleMediaKey: Int, CaseIterable {
    case volumeUp = 0, volumeDown = 1, mute = 7, playPause = 16
    init?(button: AppleRemoteButton) {
        switch button {
        case .volumeUp: self = .volumeUp
        case .volumeDown: self = .volumeDown
        case .mute: self = .mute
        case .playPause: self = .playPause
        default: return nil
        }
    }
    var source: UInt16 {
        switch self {
        case .volumeUp: return 0x80
        case .volumeDown: return 0x81
        case .mute: return RemoteButtonLayout.mute
        case .playPause: return RemoteButtonLayout.playPause
        }
    }
}

struct AppleMediaPolicy {
    enum Origin { case selected, other, unknown }
    private struct Edge { let key: AppleMediaKey; let down: Bool; let time: TimeInterval }
    private var edges: [Edge] = []
    private var nativeHolds: [AppleMediaKey:TimeInterval] = [:]
    var owned: Set<AppleMediaKey> = []
    mutating func reset() { edges.removeAll(); nativeHolds.removeAll() }
    mutating func note(_ key: AppleMediaKey, down: Bool, time: TimeInterval) {
        guard time.isFinite, time >= 0 else { return }
        if !down, let expiry = nativeHolds[key] { nativeHolds[key] = min(expiry,time+0.1) }
        edges.removeAll { time - $0.time > 0.2 }
        edges.append(Edge(key:key,down:down,time:time))
        if edges.count > 16 { edges.removeFirst(edges.count-16) }
    }
    mutating func suppress(_ key: AppleMediaKey, down: Bool, repeating: Bool,
                           time: TimeInterval, origin: Origin, synthetic: Bool) -> Bool {
        guard owned.contains(key), !synthetic, time.isFinite, time >= 0 else { return false }
        nativeHolds = nativeHolds.filter { $0.value >= time }
        switch origin {
        case .other: return false
        case .selected:
            if down {
                guard !repeating || nativeHolds[key] != nil else { return false }
                if !repeating { nativeHolds[key] = time+30 }
                return true
            }
            return nativeHolds.removeValue(forKey:key) != nil
        case .unknown:
            if nativeHolds[key] != nil, repeating || !down {
                if !down { nativeHolds[key] = nil }
                return true
            }
            // Only consume a matching physical edge once. Do not classify every
            // media key during the remote's connection as belonging to it.
            guard down, !repeating, let index = edges.firstIndex(where: {
                $0.key == key && $0.down == down && abs(time - $0.time) <= 0.08
            }) else { return false }
            edges.remove(at:index)
            if down { nativeHolds[key] = time+30 }
            return true
        }
    }
}

// On Apple silicon the HID-stage NX event can still carry mach ticks, whereas
// session-stage copies carry nanoseconds. Pick the representation consistent
// with the current mach clock; never compare different units with HID edges.
enum AppleMediaClock {
    struct Sample { let seconds: TimeInterval; let rawTicks: Bool }
    static func normalize(_ timestamp: UInt64, ticksToSeconds: Double, now: TimeInterval) -> Sample? {
        guard timestamp > 0, ticksToSeconds.isFinite, ticksToSeconds > 0, now.isFinite, now >= 0 else { return nil }
        let ticks = Double(timestamp) * ticksToSeconds
        let nanos = Double(timestamp) / 1e9
        let useTicks = abs(ticks - now) <= abs(nanos - now)
        let seconds = useTicks ? ticks : nanos
        guard seconds.isFinite, abs(seconds - now) <= 1 else { return nil }
        return Sample(seconds:seconds,rawTicks:useTicks)
    }
}
